minihack-d3qn:
  env: MiniHack-D3QN-v0
  framework: torch
  num_gpus: 1
  env_config:
    obs_keys: pixel
    input_shape:
      width: 640
      height: 480
  double_q: True
  dueling: True
  gamma:
    grid_search:
      - .99
      - .999
  lr:
    grid_search:
      - .0001
      - .001
  replay_buffer_config:
    type: MultiAgentPrioritizedReplayBuffer
    capacity: 10000
    learning_starts: 10000
  target_network_update_freq:
    grid_search:
      - 5000
      - 10000
      - 50000
  rollout_fragment_length: 4
  train_batch_size: 32
  horizon: 10000000
  exploration_config:
    epsilon_timesteps: 200000
    final_epsilon: .01
  hiddens:
    grid_search:
      - [256]
      - [512]
  compress_observations: True
  logger_config:
    wandb:
      project: "minihack-rl"
      group: "dqn"
      api_key_file: ./wandb_api_key_file
